version: "3"
services:
  ## IPFS Cluster #################################
  #################################################

  ipfs-node:
    image: ipfs/go-ipfs:$IPFS_NODE_VERSION
    container_name: $CONT_IPFS_NODE
    restart: on-failure
    volumes:
      - $EXTERNAL_VOLUME/ipfs/daemon/staging:/export
      - $EXTERNAL_VOLUME/ipfs/daemon/data:/data/ipfs
    ports:
      - "8080:8080"
    networks:
      backend:
        ipv4_address: 172.15.0.8

  ipfs-cluster:
    image: ipfs/ipfs-cluster:$IPFS_CLUSTER_VERSION
    container_name: $CONT_IPFS_CLUSTER
    depends_on:
      - ipfs-node
    environment:
      CLUSTER_PEERNAME: "Subsocial Cluster"
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-node/tcp/5001
      CLUSTER_CRDT_TRUSTERPEERS: '*' # Trust all peers in Cluster (initially)
      CLUSTER_RESTAPI_CORSALLOWEDORIGINS: '${OFFCHAIN_URL}'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
    ports:
      - "127.0.0.1:9094:9094"
    volumes:
      - $EXTERNAL_VOLUME/ipfs/cluster:/data/ipfs-cluster
    networks:
      backend:
        ipv4_address: 172.15.0.9

#################################################
#################################################