version: "3"
services:

  ipfs-node:
    image: ipfs/go-ipfs:$IPFS_NODE_VERSION
    container_name: $CONT_IPFS_NODE
    restart: on-failure
    volumes:
      - $EXTERNAL_VOLUME/ipfs/daemon/staging:/export
      - $EXTERNAL_VOLUME/ipfs/daemon/data:/data/ipfs
    ports:
      - "8080:8080"
      - "5001:5001"
    networks:
      backend:
        ipv4_address: $IPFS_NODE_IP

  ipfs-cluster:
    image: ipfs/ipfs-cluster:$IPFS_CLUSTER_VERSION
    container_name: $CONT_IPFS_CLUSTER
    restart: on-failure
    depends_on:
      - ipfs-node
    environment:
      CLUSTER_PEERNAME: "Subsocial Cluster"
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-node/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster (initially)
      CLUSTER_RESTAPI_CORSALLOWEDORIGINS: '${OFFCHAIN_URL}'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9094:9094"
      - "9096:9096"
    volumes:
      - $CLUSTER_CONFIG_FOLDER:/data/ipfs-cluster
    networks:
      backend:
        ipv4_address: $IPFS_CLUSTER_IP
