version: "3.2"
services:
  nginx:
    build: ../nginx
    image: dappforce/subsocial-proxy:$PROXY_VERSION
    container_name: $CONT_PROXY
    restart: on-failure
    ports:
      - "80:80"
    networks:
      backend:
        ipv4_address: $NGINX_PROXY_IP
