version: "3"
services:
  postgres:
    image: postgres:$POSTGRES_VERSION
    container_name: $CONT_POSTGRES
    restart: on-failure
    environment:
      POSTGRES_DB: subsocial
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: $POSTGRES_IP

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTICSEARCH_VERSION
    container_name: $CONT_ELASTICSEARCH
    restart: on-failure
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      MAX_MAP_COUNT: "64000"
      discovery.type: "single-node"
      cluster.name: "subsocial-cluster"
      node.name: "subsocial-node"
      network.host: "$ELASTICSEARCH_IP"
      http.port: "9200"
      http.cors.enabled: "true"
      http.cors.allow-credentials: "true"
      http.cors.allow-origin: "*"
      http.cors.allow-methods: "GET"
      http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Access-Control-Allow-Headers,Accept"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      backend:
        ipv4_address: $ELASTICSEARCH_IP

  offchain:
    image: dappforce/subsocial-offchain:$OFFCHAIN_VERSION
    container_name: $CONT_OFFCHAIN
    depends_on:
      - postgres
      - elasticsearch
    restart: on-failure
    environment:
      - NODE_ENV=production
      - SUBSTRATE_URL=$SUBSTRATE_RPC_URL
      - PGHOST=$POSTGRES_IP
      - ES_NODE_URL=$ELASTIC_URL
      - IPFS_NODE_URL=$IPFS_NODE_URL
      - IPFS_READ_ONLY_NODE_URL=$IPFS_READ_ONLY_NODE_URL
      - IPFS_CLUSTER_URL=$IPFS_CLUSTER_URL
      - CORS_ALLOWED_ORIGIN=$OFFCHAIN_CORS
    ports:
      - "3001:3001"
      - "3011:3011"
    networks:
      backend:
        ipv4_address: $OFFCHAIN_IP
