# IMPORTANT: You should include elasticsearch.yml and ipfs.yml with this docker-compose file.

version: "3.2"
services:
  postgres:
    image: postgres:$POSTGRES_VERSION
    container_name: $CONT_POSTGRES
    restart: on-failure
    environment:
      POSTGRES_DB: subsocial
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    volumes:
      - postgres_data:/var/lib/postgresql/data

  offchain:
    image: dappforce/subsocial-offchain:$OFFCHAIN_VERSION
    container_name: $CONT_OFFCHAIN
    depends_on:
      - $SERVICE_POSTGRES
      - $SERVICE_ELASTICSEARCH
    restart: on-failure
    command: $OFFCHAIN_CUSTOM_CMD
    environment:
      - NODE_ENV=production
      - SUBSTRATE_URL=$SUBSTRATE_RPC_URL
      - PGHOST=$SERVICE_POSTGRES
      - ES_NODE_URL=$ES_URL
      - ES_OFFCHAIN_USER=$ES_OFFCHAIN_USER
      - ES_OFFCHAIN_PASSWORD=$ES_OFFCHAIN_PASSWORD
      - ES_READONLY_USER=$ES_READONLY_USER
      - ES_READONLY_PASSWORD=$ES_READONLY_PASSWORD
      - IPFS_NODE_URL=$IPFS_NODE_URL
      - IPFS_READ_ONLY_NODE_URL=$IPFS_READ_ONLY_NODE_URL
      - IPFS_CLUSTER_URL=$IPFS_CLUSTER_URL
      - CORS_ALLOWED_ORIGIN=$OFFCHAIN_CORS
    volumes:
      - $OFFCHAIN_STATE:/app/build/state
    ports:
      - "$OFFCHAIN_API_PORT:3001"
      - "$OFFCHAIN_WS_PORT:3011"

volumes:
  postgres_data:
