version: "3.2"
services:
  postgres:
    image: postgres:$POSTGRES_VERSION
    container_name: $CONT_POSTGRES
    restart: on-failure
    environment:
      POSTGRES_DB: subsocial
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: $POSTGRES_IP

  offchain:
    image: dappforce/subsocial-offchain:$OFFCHAIN_VERSION
    container_name: $CONT_OFFCHAIN
    depends_on:
      - postgres
      - elasticsearch
    restart: on-failure
    environment:
      - NODE_ENV=production
      - SUBSTRATE_URL=$SUBSTRATE_RPC_URL
      - PGHOST=$POSTGRES_IP
      - ES_NODE_URL=$ELASTIC_URL
      - IPFS_NODE_URL=$IPFS_NODE_URL
      - IPFS_READ_ONLY_NODE_URL=$IPFS_READ_ONLY_NODE_URL
      - IPFS_CLUSTER_URL=$IPFS_CLUSTER_URL
      - CORS_ALLOWED_ORIGIN=$OFFCHAIN_CORS
    volumes:
      - $EXTERNAL_VOLUME/offchain_state:/app/build/state
    ports:
      - "3001:3001"
      - "3011:3011"
    networks:
      backend:
        ipv4_address: $OFFCHAIN_IP
