version: "3.4"
services:
  offchain-api:
    image: dappforce/subsocial-offchain:$OFFCHAIN_VERSION
    container_name: $CONT_OFFCHAIN_API
    restart: always
    command: $OFFCHAIN_API_CMD
    environment:
      - NODE_ENV=production
      - SUBSTRATE_URL=$SUBSTRATE_RPC_URL
      - PGHOST=$SERVICE_POSTGRES
      - PGDATABASE=$DB_NAME
      - PGUSER=$DB_USER
      - PGPASSWORD=$DB_PASS
      - PGPORT=$OFFCHAIN_POSTGRES_PORT
      - ES_NODE_URL=$ES_URL
      - ES_OFFCHAIN_USER=$ES_OFFCHAIN_USER
      - ES_OFFCHAIN_PASSWORD=$ES_OFFCHAIN_PASSWORD
      - ES_READONLY_USER=$ES_READONLY_USER
      - ES_READONLY_PASSWORD=$ES_READONLY_PASSWORD
      - IPFS_NODE_URL=$IPFS_NODE_URL
      - IPFS_READ_ONLY_NODE_URL=$IPFS_READ_ONLY_NODE_URL
      - IPFS_CLUSTER_URL=$IPFS_CLUSTER_URL
      - CORS_ALLOWED_ORIGIN=$OFFCHAIN_CORS
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - EMAIL_FROM=$EMAIL_FROM
      - FAUCET_MNEMONIC=$FAUCET_MNEMONIC
      - FAUCET_DRIP_AMOUNT=$FAUCET_DRIP_AMOUNT
      - RECAPTCHA_KEY=$RECAPTCHA_KEY
      - LOG_LEVEL=debug
    ports:
      - "$EXPOSE_IP:$OFFCHAIN_API_PORT:3001"

  offchain-subscriber:
    image: dappforce/subsocial-offchain:$OFFCHAIN_VERSION
    container_name: $CONT_OFFCHAIN_SUBSCRIBER
    restart: always
    command: $OFFCHAIN_SUBSCRIBER_CMD
    environment:
      - NODE_ENV=production
      - SUBSTRATE_URL=$SUBSTRATE_RPC_URL
      - PGHOST=$SERVICE_POSTGRES
      - PGDATABASE=$DB_NAME
      - PGUSER=$DB_USER
      - PGPASSWORD=$DB_PASS
      - PGPORT=$OFFCHAIN_POSTGRES_PORT
      - ES_NODE_URL=$ES_URL
      - ES_OFFCHAIN_USER=$ES_OFFCHAIN_USER
      - ES_OFFCHAIN_PASSWORD=$ES_OFFCHAIN_PASSWORD
      - IPFS_READ_ONLY_NODE_URL=$IPFS_READ_ONLY_NODE_URL
      - LOG_LEVEL=debug
    volumes:
      - $OFFCHAIN_STATE:/app/build/state
    ports:
      - "$EXPOSE_IP:$OFFCHAIN_WS_PORT:3011"
