version: "3.2"
services:
  web-ui:
    image: dappforce/subsocial-ui:$WEBUI_VERSION
    container_name: $CONT_WEBUI
    restart: on-failure
    environment:
      - SUBSTRATE_RPC_URL=$SUBSTRATE_RPC_URL
      - OFFCHAIN_URL=$OFFCHAIN_URL
      - OFFCHAIN_WS=$OFFCHAIN_WS
      - ES_URL=$ES_URL
      - APPS_URL=$APPS_URL
      - IPFS_URL=$IPFS_READ_ONLY_NODE_URL
    networks:
      backend:
        ipv4_address: $WEBUI_DOCKER_IP
