http:
  services:
    ws-service:
      loadbalancer:
        servers:
          - url: "http://localhost:9944"

    rpc-service:
      loadbalancer:
        servers:
          - url: "http://localhost:9933"

  routers:
    ws-router:
      rule: "Host(`localhost`)"
      service: ws-service
      middlewares:
        - node-common
      tls:
        certResolver: "le"

    rpc-router:
      rule: "Host(`localhost`) && Path(`/http`)"
      service: rpc-service
      middlewares:
        - node-common
      tls:
        certResolver: "le"

  middlewares:
    node-common:
      headers:
        accessControlAllowMethods: [ GET, OPTIONS, POST ]
        accessControlAllowOriginList: [ https://app.subsocial.network,https://sub.id,https://polkaverse.com,https://polkadot.js.org ]
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: true
        hostsProxyHeaders: true
