http:
  services:
    ws-service:
      loadbalancer:
        healthcheck:
          path: /health
          port: 8833
          interval: "5s"
          timeout: "2s"
        passHostHeader: false
        servers:
          - url: "http://localhost:8844"

    rpc-service:
      loadbalancer:
        healthcheck:
          path: /health
          interval: "5s"
          timeout: "2s"
        passHostHeader: false
        servers:
          - url: "http://localhost:8833"

  routers:
    ws-router:
      rule: "Host(`para.subsocial.network`) && Path(`/`)"
      service: ws-service
      middlewares:
        - secure
      tls:
        certResolver: "le"

    rpc-router:
      rule: "Host(`para.subsocial.network`) && Path(`/http`)"
      service: rpc-service
      middlewares:
        - secure-rpc
      tls:
        certResolver: "le"

  middlewares:
    secure-rpc:
      chain:
        middlewares:
          - handle-preflight
          - secure

    secure:
      headers:
        accessControlMaxAge: 300
        addVaryHeader: true
        frameDeny: true
        contentTypeNosniff: true

    handle-preflight:
      headers:
        accessControlAllowOriginList:
          - https://app.subsocial.network
          - https://sub.id
          - https://polkaverse.com
          - https://polkadot.js.org
        accessControlAllowMethods: [ OPTIONS, POST ]
        accessControlAllowHeaders:
          - Content-Type
